kind: MLApp
metadata:
  name: tensorflow
spec:
  package_manager: "pip3"
  default_mount_path: "/notebooks"
  tasks:
  - name: install-guides
    type: init
    resources:
    - name: worker
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 0
      allowFail: true
      images:
        gpu: "kuberlab/tensorflow:gpu-36-{{.tensorflow_version.value}}-full"
        cpu: "kuberlab/tensorflow:cpu-36-{{.tensorflow_version.value}}-full"
      command: >-
        git clone https://github.com/lsheiba/tf_tutorials tutorials
      workdir: "$CODE_DIR"
      resources:
        accelerators:
          gpu: 0
        requests:
          cpu: "100m"
          memory: 1Gi
        limits:
          cpu: "1"
          memory: 4Gi
      default_volume_mapping: true
  - name: standalone
    resources:
    - name: worker
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 0
      images:
        gpu: "kuberlab/tensorflow:gpu-36-{{.tensorflow_version.value}}-full"
        cpu: "kuberlab/tensorflow:cpu-36-{{.tensorflow_version.value}}-full"
      command: python hello-tensorflow.py
      workdir: "$SRC_DIR"
      resources:
        accelerators:
          gpu: 0
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 1000m
          memory: 8Gi
      default_volume_mapping: true
  uix:
  {{- if .jupyter.value }}
  - name: jupyter
    displayName: Jupyter
    images:
      gpu: "kuberlab/tensorflow:gpu-36-{{.tensorflow_version.value}}-full"
      cpu: "kuberlab/tensorflow:cpu-36-{{.tensorflow_version.value}}-full"
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 1000m
        memory: 4Gi
    ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: http
    default_volume_mapping: true
  {{- end }}
  {{- if .tensorboard.value }}
  - name: tensorboard
    displayName: Tensorboard
    {{- if eq (index .tensorflow_version.value 0) 50 }}
    command: "tensorboard --logdir=$TRAINING_DIR --bind_all"
    {{- else }}
    command: "tensorboard --logdir=$TRAINING_DIR"
    {{- end }}
    images:
      gpu: "kuberlab/tensorflow:gpu-36-{{.tensorflow_version.value}}-full"
      cpu: "kuberlab/tensorflow:cpu-36-{{.tensorflow_version.value}}-full"
    ports:
    - port: 6006
      targetPort: 6006
      protocol: TCP
      name: http
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 1000m
        memory: 2Gi
    volumes:
    - name: training
  {{- end }}
  volumes:
  - name: training
    clusterStorage: {{ .storage.value }}
  - isLibDir: true
    name: lib
    clusterStorage: {{ .storage.value }}
  - name: data
    {{- if .dataset.value }}
    datasetFS:
      workspace: {{ .dataset.workspace }}
      dataset: {{ .dataset.value }}
      version: {{ .dataset.version }}
    {{- else }}
    clusterStorage: {{ .storage.value }}
    {{- end }}
  - mountPath: /notebooks
    name: code
    subPath: code
    clusterStorage: {{ .storage.value }}
