storage:
 value: default
 wizard:
   name: "Storage Configuration"
   kind: cluster_storage

tensorflow_version:
  value: "1.14"
  wizard:
    name: "Tensorflow version"
    kind: select
    options:
    - "1.14"
    - "2.1.0"

jupyter:
  value: true
  wizard:
    name: Install Jupyter
    kind: boolean

tensorboard:
  value: true
  wizard:
    name: Install Tensorboard
    kind: boolean

src:
  value: https://github.com/lsheiba/tf_tutorials
  accountId: ''
  revision: ''
  wizard:
    name: "Source Code"
    kind: git

dataset:
 value: ''
 version: ''
 workspace: ''
 wizard:
   name: "Dataset configuration"
   kind: dataset
